version: '3.8'
services:     
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    ports:
      - '5432:5432'      
  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  app:
    build: .      
    restart: always
    container_name: 'portfolio'
    command: gunicorn my_portfolio_website.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/app/static
    ports:
      - '8000:8000'
    environment:
      - DEBUG:0
      - DB_NAME:"portfolio"
      - DB_USER:"portfolio"
      - DB_PASSWORD:"portfolio"
      - DB_HOST:"postgres"
      - DB_PORT:5432
      - APP_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres 
    

  celery:
    build: .      
    container_name: 'demo_app_celery'
    command: celery -A my_portfolio_website worker -l info
    volumes:
      - .:/code    
    depends_on:
      - app
      - redis

  nginx:
    image: nginx:latest 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
    static_volume:         
  