# Generated by Django 5.1.3 on 2024-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
