# Generated by Django 5.1.3 on 2024-12-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_course_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
