# Generated by Django 5.1.3 on 2024-12-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
